# 05 Jun 93
#
# $Id: Makefile.BSD,v 1.1 2002/11/26 10:42:57 alex Exp $
#
.PATH:  /usr/include/net

# Uncomment this to output debug messages
#WANDEBUG_CFG =

#***************************************************************************
# don't change anything below 

PROG    	= wanconfig
BINDIR  	= /usr/sbin
.OBJDIR 	= /usr/obj${.CURDIR}
NOMAN 		=

.if defined(WANDEBUG_CFG)
CFLAGS += -DWANDEBUG_CFG
.endif

cleanall:
	\rm -f ${BINDIR}/${PROG}

.include <bsd.prog.mk>
