#
# Makefile for the Linux network (wan) device drivers.
#
# 3 Aug 2000, Christoph Hellwig <hch@infradead.org>
# Rewritten to use lists instead of if-statements.
#

EXTRA_CFLAGS=$(EXTRA_FLAGS)

wan_aften-objs		:= wan_aften_src.o wanpipe_linux_iface.o

obj-m += wan_aften.o    

